### ISSUE TITLE
Invisible vessels sometimes when firing process completes

### ISSUE THREAD

**Issue by zach2039** [zach2039/vs-beehivekiln#2]
bumblebink, Apr 22nd at 11:09 PM
> I'm not sure what causes it, but every time I fire a vessel in the center, it ends up as an "empty pile" containing 1x storage vessels. The "empty pile" needs to be broken in order to retrieve the vessel.
>
> Edit: It doesn't happen every time, just some of the time. I've had it happen twice, but I've been unable to reproduce it now lol.

**Comment by VaelophisNyx** [comment]
I've been getting this a lot, and I unfortunately have to have a client (LAN server) come retrieve things for me because if I break it, the game crashes or I don't get anything from it. The clients however see the items just fine. So I'm wondering if this is a networking issue. This would also affect singleplayer as that's a server running in the background that you are connected to

**Comment by zach2039** [comment]
Might be fixed with 1.5.2 that had minor refactors to code that calls MarkDirty, but I am keeping this open until confirmed.

**Comment by zach2039** [comment]
Seems to be better now that I am mimicking BlockEntityPitKiln's KillFire method, which sets a new ground storage block with entity, copying over required entity attributes.
